/* Cuts the pixel templates + geometry in src/anchor.js out of a reference
   capture of the Discovery window.

     node tools/make-anchor.js            print diagnostics only
     node tools/make-anchor.js --write    also rewrite src/anchor.js

   IMPORTANT: the reference must be an Alt1 capture (app: reader debug ->
   Download this capture), not a Windows screenshot.  With Windows display
   scaling on, a screenshot is the game enlarged (125% etc.) while Alt1 sees the
   game at its native size - templates cut from a screenshot never match.

   REF.origin = top-left pixel of the dark border of the module strip. */
var fs = require("fs"), path = require("path"), PNG = require("pngjs").PNG;
var root = path.join(__dirname, "..");
var loadPng = require("./pngload.js");

var REF = { file: "test/capture-satisfactory.png", origin: [949, 615] };
/* native px.  L0 = top-left of slot 1's frame = origin + (15,10).  Everything below is relative to L0. */
var GEO = {
  L0_DX: 15, L0_DY: 10,
  PITCH: 70, LINE_SPAN: 49, SLOT_SIZE: 50, SLOT_INSET: 4,
  PARCH_W: 352, PARCH_DX: 10, PARCH_DY: 5,      /* the parchment-coloured area: width, and where L0 sits inside it */
  TEXT: { dx: -65, dy: 125, w: 265, h: 60 },
  TITLE: { dx: 86, dy: -340, w: 275, h: 82 },
  MATCH_MIN: 0.88, DISTINCT_MAX: 0.8, EMPTY_CONTRAST: 16
};
var ANCHOR_BOXES = [{ dx: 0, dy: 0, w: 20, h: 11 }, { dx: 340, dy: 0, w: 20, h: 11 }];

function crop(img, x, y, w, h) {
  var o = new PNG({ width: w, height: h });
  for (var j = 0; j < h; j++) for (var i = 0; i < w; i++) {
    var p = ((y + j) * img.width + x + i) * 4, q = (j * w + i) * 4;
    o.data[q] = img.data[p]; o.data[q + 1] = img.data[p + 1]; o.data[q + 2] = img.data[p + 2]; o.data[q + 3] = 255;
  }
  return o;
}
function countMatches(img, needle) {
  var hits = [];
  for (var y = 0; y + needle.height <= img.height; y++) for (var x = 0; x + needle.width <= img.width; x++) {
    var ok = true;
    for (var j = 0; j < needle.height && ok; j++) for (var i = 0; i < needle.width; i++) {
      var p = ((y + j) * img.width + x + i) * 4, q = (j * needle.width + i) * 4;
      if (Math.abs(img.data[p] - needle.data[q]) + Math.abs(img.data[p + 1] - needle.data[q + 1]) + Math.abs(img.data[p + 2] - needle.data[q + 2]) > 30) { ok = false; break; }
    }
    if (ok) hits.push([x, y]);
  }
  return hits;
}

var ref = loadPng(path.join(root, REF.file));
var anchorPngs = ANCHOR_BOXES.map(function (b) { return crop(ref, REF.origin[0] + b.dx, REF.origin[1] + b.dy, b.w, b.h); });
anchorPngs.forEach(function (a, i) { console.log("anchor " + i + " matches in the whole capture: " + JSON.stringify(countMatches(ref, a))); });

var R = require(path.join(root, "src/reader.js"))(null, GEO);
var L0 = [REF.origin[0] + GEO.L0_DX, REF.origin[1] + GEO.L0_DY];
var cands = R.findCandidates(ref);
console.log("strip-shaped parchment candidates: " + cands.length + "  first: " + JSON.stringify(cands[0]));
var loc = R.locate(ref);
console.log("scale-free locate: " + (loc ? "x0 " + loc.x0 + " y0 " + loc.y0 + " scale " + loc.s.toFixed(4) + " score " + loc.score.toFixed(1) : "FAILED") + "   (expected " + L0 + ", scale 1)");
var rd = R.readBuffer(ref, L0[0], L0[1], 1, []);
console.log("slot contrast: " + rd.fps.map(function (f) { return f.contrast.toFixed(1); }).join(" "));
var mx = -1; for (var a = 0; a < 5; a++) for (var b = a + 1; b < 5; b++) mx = Math.max(mx, R.similarity(rd.fps[a], rd.fps[b]));
console.log("different modules, max similarity: " + mx.toFixed(3));
console.log("rating: " + (rd.word ? JSON.stringify({ level: rd.level, ratio: +rd.word.ratio.toFixed(3), gap: rd.word.gap, hue: Math.round(rd.word.hue), pg: +rd.word.pg.toFixed(2), h: rd.word.h }) : "NOT READ"));
console.log("blueprint hash: " + rd.title);

if (process.argv.indexOf("--write") >= 0) {
  var out = "/* GENERATED by tools/make-anchor.js from " + REF.file + " - do not hand-edit.\n" +
    "   Coordinates are relative to the top-left corner of the module strip. */\n" +
    "(function (root, factory) {\n  if (typeof module === \"object\" && module.exports) module.exports = factory();\n  else root.ProtoAnchor = factory();\n})(this, function () {\n  return " +
    JSON.stringify(Object.assign({
      ANCHORS: ANCHOR_BOXES.map(function (bx, i) { return { dx: bx.dx, dy: bx.dy, png: "data:image/png;base64," + PNG.sync.write(anchorPngs[i]).toString("base64") }; })
    }, GEO), null, 1).replace(/\n/g, "\n  ") + ";\n});\n";
  fs.writeFileSync(path.join(root, "src/anchor.js"), out);
  console.log("wrote src/anchor.js (" + out.length + " bytes)");
}
