/* GENERATED by tools/make-anchor.js from test/capture-satisfactory.png - do not hand-edit.
   Coordinates are relative to the top-left corner of the module strip. */
(function (root, factory) {
  if (typeof module === "object" && module.exports) module.exports = factory();
  else root.ProtoAnchor = factory();
})(this, function () {
  return {
   "ANCHORS": [
    {
     "dx": 0,
     "dy": 0,
     "png": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAALCAYAAAB/Ca1DAAABAElEQVR4Aa3BQUoDQRBA0d/VVTXdk4ki0dxEPIC38KpewL0bN4Lg0l2iGJKZaW0lEMLoKu+Fu9ubwgkp395WG05FODHlRNQjlXLk+nLFsdDNuIo9h4azc5baszfM51TKhGUf+LFwqk52WBYqS4FqKD2lgTaOBJ0BPZXyj04KlgUIVJYCnht+jViaEYIhKuwpUxZOJ4U9S4HKc0PlHimSUM+UMlKJNlTChE4KlWXBUqDy3OAecY9oSqhnnl7XRMs0bcZcMBeUP1gWLAU8N1TukSIJcyhkvM28b1doSkQNVDEWlAPqkSnukcocorY8vnzwuV2z2RXuH565cGUcR4YRvgBkqTXujJO6RgAAAABJRU5ErkJggg=="
    },
    {
     "dx": 340,
     "dy": 0,
     "png": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAALCAYAAAB/Ca1DAAABDUlEQVR4Aa3BTWrCQACA0S+TGcdItNEQqAsXpRvppqseoTfvBUqhF7AgxQZUJNHMj2UoaUMR3fhe9Pz0eORKhjpCrtZbriYbIbgyyQV9JWntjeUS+ZA3dO1lwXy44Y+ly306gkXPEbyXPbrk3WxMVxHvAc1JZQO5ZFlaZk3MoucwxqKUpCXnhabrsDYEKhEEpvb8KhS7lWGaS5al5RTBP8nkBp2lCD3A1B6dpXSlhSKY5pJZE6OUpEvQIUTM20eFEDGBzlICnaWcY4zFGEsgJ7cTvPP8iBhtjyQ3A+pNhfeOls5S/KHC1J60UOxWhlPky+sX2hl846mSmEMT0ViPiI7cjyXeO87pK4kxltY3vF9hsrVgmowAAAAASUVORK5CYII="
    }
   ],
   "L0_DX": 15,
   "L0_DY": 10,
   "PITCH": 70,
   "LINE_SPAN": 49,
   "SLOT_SIZE": 50,
   "SLOT_INSET": 4,
   "PARCH_W": 352,
   "PARCH_DX": 10,
   "PARCH_DY": 5,
   "TEXT": {
    "dx": -65,
    "dy": 125,
    "w": 265,
    "h": 60
   },
   "TITLE": {
    "dx": 86,
    "dy": -340,
    "w": 275,
    "h": 82
   },
   "MATCH_MIN": 0.93,
   "MATCH_MARGIN": 0.03,
   "DISTINCT_MAX": 0.95,
   "EMPTY_EDGE": 5
  };
});
